# Generated by Django 5.0.6 on 2024-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Rol', models.CharField(choices=[(1, 'Student'), (2, 'Professor'), (3, 'Other')], default=None, max_length=200)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[(1, 'Balanced power flow'), (2, 'Unbalanced power flow'), (3, 'State Estimator')], default=None, max_length=200)),
            ],
        ),
    ]
