# Generated by Django 5.0.6 on 2024-06-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powerflow',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='powerflow',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='powerflow',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='powerflow',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='powerflow',
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='powerflow',
            name='Type',
        ),
    ]
