# Generated by Django 5.0.6 on 2024-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_rename_email_powerflow_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerflow',
            name='rol',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Professor'), ('3', 'Other')], default=None, max_length=200),
        ),
    ]
