# Generated by Django 5.0.6 on 2024-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_powerflow_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerflow',
            name='lines',
            field=models.TextField(default=' ', max_length=2000),
        ),
        migrations.AddField(
            model_name='powerflow',
            name='loads',
            field=models.TextField(default=' ', max_length=2000),
        ),
        migrations.AddField(
            model_name='powerflow',
            name='nodes',
            field=models.TextField(default=' ', max_length=2000),
        ),
    ]
