# Generated by Django 5.0.6 on 2024-06-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_stateestimator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndesaCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PowerFlow',
        ),
        migrations.DeleteModel(
            name='StateEstimator',
        ),
    ]
