# Generated by Django 5.0.6 on 2024-06-27 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_endesacredentials_delete_powerflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endesacredentials',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
